const BLOCKFROST_API_KEY = import.meta.env.VITE_BLOCKFROST_API_KEY;
const BLOCKFROST_URL = import.meta.env.VITE_BLOCKFROST_URL;
const CARDANO_NETWORK = import.meta.env.VITE_CARDANO_NETWORK;
const ORDER_ADDRESS = import.meta.env.VITE_ORDER_ADDRESS;
const CONTRACT = import.meta.env.VITE_CONTRACT;
const TOKEN_POLICY_ID = import.meta.env.VITE_TOKEN_POLICY_ID;
const USDM_POLICY_ID = import.meta.env.VITE_USDM_POLICY_ID;
const TRANSACTION_ID = import.meta.env.VITE_TRANSACTION_ID;

export {
  BLOCKFROST_API_KEY,
  BLOCKFROST_URL,
  CARDANO_NETWORK,
  ORDER_ADDRESS,
  CONTRACT,
  TOKEN_POLICY_ID,
  USDM_POLICY_ID,
  TRANSACTION_ID,
};
