const LOVELACE_IN_ADA = 1_000_000n;
const NUMBER_OF_HEX = 16;
const NUMBER_PAD_START = 2;
const COLATERAL_UTXO_ADA = 2_000_000n;
export { LOVELACE_IN_ADA, NUMBER_OF_HEX, NUMBER_PAD_START, COLATERAL_UTXO_ADA };
